#!/bin/bash

function error()
{
    echo -e "\n\n\n\tERROR: Please fix the errors shown above and rerun- check the output above\n\n\n"
    exit 1
}

find . -name "*.py" | xargs pylint --rcfile pylint.rc || error
find . -name "*.js" -not -path "*./node_modules/*.js" -not -path "*./static/*.js" | xargs ./node_modules/jshint/bin/jshint --verbose || error
